/*
 *  Developed by Vasileios Karachountris and Eva Konstantopoulou for Computer Engineering and
 *  Informatics Department, to be used in the Database Laboratory Project that they submit.
 *  All Rights Reserved.
 */
package mainpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import static mainpackage.CheckConnection.url;

/**
 *
 * @author Vasilis
 */
public class checkAccounting extends javax.swing.JFrame
{

    /**
     * Creates new form checkAccounting
     */
    public checkAccounting()
    {
	initComponents();
        FillNewspaperCombo();
        Fillemployeecombo();
       // Display();
    }

     private void FillNewspaperCombo()
    {
	try
	{
	    Connection con = DriverManager.getConnection(url);
	    String value0 = UsernameText.getText();
            String sql1 = "select newspaper.newspaper_name from newspaper inner join employee on employee.newspaper_name = newspaper.newspaper_name inner join admin_employee on admin_employee.admin_email = employee.employee_email where employee_login =  ? ";
	    PreparedStatement pst = con.prepareStatement(sql1);
	    pst.setString(1,value0);
            System.out.println(value0);
            ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
                String name = rs.getString("newspaper_name");
                NewspaperCombo.addItem(name);	
            }
            
        
	    con.close();
	}
	catch(Exception e)
        {
            
        }
    } 
     private void Fillemployeecombo()
    {
	try
	{
	    Connection con = DriverManager.getConnection(url);
	    String value0 = UsernameText.getText();
            String value1 = NewspaperCombo.getSelectedItem().toString();
            String sql2 = "select employee_email from employee inner join newspaper on newspaper.newspaper_name = employee.newspaper_name where employee.newspaper_name = ?";
            PreparedStatement pstm = con.prepareStatement(sql2);
            pstm.setString(1,value1);
            ResultSet rs = pstm.executeQuery();
            while(rs.next())
	    {
                String name = rs.getString("employee_email");
                System.out.println(name);
                employeecombo.addItem(name);	
            }
	    
	    con.close();
	}
	catch(Exception e)
        {
            
        }
    }   
     
     
     
      private void Display()
    {
	try
	{
	    Connection con = DriverManager.getConnection(url);
	    Integer value0 = Integer.parseInt(monthText.getText());
            String value1 = selectioncombo.getSelectedItem().toString();
            String value2 = NewspaperCombo.getSelectedItem().toString();
            if(value1=="Total"){
             String sql = "select sum (employee_salary) from employee where newspaper_name = ? ";
             System.out.println(value1);
             PreparedStatement pst = con.prepareStatement(sql);
             pst.setString(1,value2);
             System.out.println(value2);
             ResultSet rs = pst.executeQuery();
             while(rs.next())
             {
                String sum = rs.getString("sum(employee_salary)");
                System.out.println(sum);
                if (value2=="Bhma")
                {Integer salary = 6895 *value0;
                DisplayText.setText(salary.toString());}
                else if (value2=="Thema")
                {Integer salary = 7110 *value0;
                DisplayText.setText(salary.toString());}
                
             }
            }
            else if(value1=="Per employee"){
             String value3 = employeecombo.getSelectedItem().toString();
             String sql = "select employee_salary from employee where employee_email = ? ";
             PreparedStatement pst = con.prepareStatement(sql);
             pst.setString(1,value3);
             ResultSet rs = pst.executeQuery();
             while(rs.next())
             {
                Integer name = rs.getInt("employee_salary");
                System.out.println(name);
                Integer salary = value0* name;
                DisplayText.setText(salary.toString());
             }
            }
            
	    con.close();
	}
	catch(Exception e)
        {
            
        }
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountingBack = new javax.swing.JButton();
        displayReport = new javax.swing.JButton();
        monthText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        selectioncombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        employeecombo = new javax.swing.JComboBox<>();
        okbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        UsernameText = new javax.swing.JTextField();
        NewspaperCombo = new javax.swing.JComboBox<>();
        DisplayText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountingBack.setText("Back");
        accountingBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountingBackActionPerformed(evt);
            }
        });

        displayReport.setText("DISPLAY REPORT");
        displayReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayReportActionPerformed(evt);
            }
        });

        monthText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Month Span:");

        selectioncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Per employee", "Total" }));
        selectioncombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectioncomboActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Per employee/Total");

        jLabel3.setText("The cost for the choices you have picked:");

        jLabel4.setText("Please select the employee for whom you want to see the cost:");

        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });

        jLabel5.setText("Please enter your username:");

        NewspaperCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewspaperComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayReport)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplayText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(monthText, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(selectioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(okbutton)
                            .addComponent(NewspaperCombo, 0, 111, Short.MAX_VALUE)
                            .addComponent(employeecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountingBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountingBack)
                    .addComponent(jLabel5)
                    .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(monthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NewspaperCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(selectioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(okbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(employeecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(displayReport)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DisplayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountingBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_accountingBackActionPerformed
    {//GEN-HEADEREND:event_accountingBackActionPerformed
        new admin_employee().setVisible(true); //Go back to the previous window.
	this.dispose(); // Close previous window.
    }//GEN-LAST:event_accountingBackActionPerformed

    private void monthTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_monthTextActionPerformed
    {//GEN-HEADEREND:event_monthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // TODO add your handling code here:
        String value1 = selectioncombo.getSelectedItem().toString();   
        if(value1=="Total")
        {FillNewspaperCombo();}
        else if(value1=="Per employee")
        {Fillemployeecombo();
        FillNewspaperCombo();}
    }//GEN-LAST:event_okbuttonActionPerformed

    private void selectioncomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectioncomboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_selectioncomboActionPerformed

    private void displayReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayReportActionPerformed
        // TODO add your handling code here:
        Display();
    }//GEN-LAST:event_displayReportActionPerformed

    private void NewspaperComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewspaperComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewspaperComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	
        
        /* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try
	{
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
	    {
		if ("Nimbus".equals(info.getName()))
		{
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex)
	{
	    java.util.logging.Logger.getLogger(checkAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex)
	{
	    java.util.logging.Logger.getLogger(checkAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex)
	{
	    java.util.logging.Logger.getLogger(checkAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex)
	{
	    java.util.logging.Logger.getLogger(checkAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable()
	{
	    public void run()
	    {
		new checkAccounting().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DisplayText;
    private javax.swing.JComboBox<String> NewspaperCombo;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JButton accountingBack;
    private javax.swing.JButton displayReport;
    private javax.swing.JComboBox<String> employeecombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField monthText;
    private javax.swing.JButton okbutton;
    private javax.swing.JComboBox<String> selectioncombo;
    // End of variables declaration//GEN-END:variables
}
