/*
 *  Developed by Vasileios Karachountris and Eva Konstantopoulou for Computer Engineering and
 *  Informatics Department, to be used in the Database Laboratory Project that they submit.
 *  All Rights Reserved.
 */
package mainpackage;

/**
 *
 * @author Vasilis
 */
public class chief_editor extends javax.swing.JFrame
{

    /**
     * Creates new form chief_editor
     */
    public chief_editor()
    {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        defineOrder = new javax.swing.JButton();
        newSubmit = new javax.swing.JButton();
        newCategory = new javax.swing.JButton();
        seeArticles = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        chief_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        defineOrder.setText("Define Order");
        defineOrder.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                defineOrderActionPerformed(evt);
            }
        });

        newSubmit.setText("Submit Article");
        newSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newSubmitActionPerformed(evt);
            }
        });

        newCategory.setText("Insert New Category");
        newCategory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newCategoryActionPerformed(evt);
            }
        });

        seeArticles.setText("See Articles");
        seeArticles.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                seeArticlesActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Action");

        chief_back.setText("Back");
        chief_back.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chief_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seeArticles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(defineOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chief_back, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chief_back)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seeArticles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defineOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newSubmit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newCategory)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void defineOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_defineOrderActionPerformed
    {//GEN-HEADEREND:event_defineOrderActionPerformed
        new defineOrderArticle().setVisible(true); //Open the tab to define article order.
	this.dispose(); // Close previous window.
    }//GEN-LAST:event_defineOrderActionPerformed

    private void newSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newSubmitActionPerformed
    {//GEN-HEADEREND:event_newSubmitActionPerformed
        new submitArticleforchief().setVisible(true); //open new window to submit article
	this.dispose();//to close the current jframe
    }//GEN-LAST:event_newSubmitActionPerformed

    private void newCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newCategoryActionPerformed
    {//GEN-HEADEREND:event_newCategoryActionPerformed
        new newCat().setVisible(true); //open new window to make a new category. 
	this.dispose();//to close the current jframe
    }//GEN-LAST:event_newCategoryActionPerformed

    private void seeArticlesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_seeArticlesActionPerformed
    {//GEN-HEADEREND:event_seeArticlesActionPerformed
        new seeArticle().setVisible(true); //Open the tab to review the articles
	this.dispose(); // Close previous window.
    }//GEN-LAST:event_seeArticlesActionPerformed

    private void chief_backActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chief_backActionPerformed
    {//GEN-HEADEREND:event_chief_backActionPerformed
        new LoginPage().setVisible(true); //Go back to the previous window.
	this.dispose(); // Close previous window.
    }//GEN-LAST:event_chief_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try
	{
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
	    {
		if ("Nimbus".equals(info.getName()))
		{
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex)
	{
	    java.util.logging.Logger.getLogger(chief_editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex)
	{
	    java.util.logging.Logger.getLogger(chief_editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex)
	{
	    java.util.logging.Logger.getLogger(chief_editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex)
	{
	    java.util.logging.Logger.getLogger(chief_editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable()
	{
	    public void run()
	    {
		new chief_editor().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chief_back;
    private javax.swing.JButton defineOrder;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton newCategory;
    private javax.swing.JButton newSubmit;
    private javax.swing.JButton seeArticles;
    // End of variables declaration//GEN-END:variables
}
