/*
 *  Developed by Vasileios Karachountris and Eva Konstantopoulou for Computer Engineering and
 *  Informatics Department, to be used in the Database Laboratory Project that they submit.
 *  All Rights Reserved.
 */
package mainpackage;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import static mainpackage.CheckConnection.url;

/**
 *
 * @author Vasilis
 */
public class newCat extends javax.swing.JFrame
{

    /**
     * Creates new form newCat
     */
    public newCat()
    {
	initComponents();
	FillCombo();
	FillCombo1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCatBack = new javax.swing.JButton();
        chiefEmail = new javax.swing.JComboBox<>();
        parentCat = new javax.swing.JComboBox<>();
        newCatName = new javax.swing.JTextField();
        newCatDesc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        insertNewCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newCatBack.setText("Back");
        newCatBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCatBackActionPerformed(evt);
            }
        });

        chiefEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiefEmailActionPerformed(evt);
            }
        });

        parentCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no parent category" }));
        parentCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentCatActionPerformed(evt);
            }
        });

        newCatName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newCatName.setText("Category Name");
        newCatName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newCatNameMouseClicked(evt);
            }
        });
        newCatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCatNameActionPerformed(evt);
            }
        });

        newCatDesc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newCatDesc.setText("Category Description");
        newCatDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newCatDescMouseClicked(evt);
            }
        });
        newCatDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCatDescActionPerformed(evt);
            }
        });

        jLabel2.setText("Chief-Editor-Email");

        jLabel3.setText("Parent Category");

        insertNewCat.setText("INSERT NEW CATEGORY");
        insertNewCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertNewCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newCatName)
                                    .addComponent(newCatDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chiefEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(parentCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newCatBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(insertNewCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCatBack)
                .addGap(18, 18, 18)
                .addComponent(insertNewCat)
                .addGap(42, 42, 42)
                .addComponent(newCatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newCatDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chiefEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(parentCat)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void FillCombo1()
    {
	try
	{ 
	    Connection con = DriverManager.getConnection(url);
	    String sql ="SELECT cat_name FROM category";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    /*
	    String sql = "SELECT chief_editor_email FROM chief_editor INNER JOIN employee ON employee_email=chief_editor_email WHERE employee_login='";
	    String sql1 = super.username1;
	    */
	    	    
	    while(rs.next())
	    {
		String name = rs.getString("cat_name");
		parentCat.addItem(name);		
	    }
	con.close();
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }   
    
    
    
    
    
    
    private void FillCombo()
    {
	try
	{
	    Connection con = DriverManager.getConnection(url);
	    String sql ="SELECT chief_editor_email FROM chief_editor";
	    /*
	    String sql = "SELECT chief_editor_email FROM chief_editor INNER JOIN employee ON employee_email=chief_editor_email WHERE employee_login='";
	    String sql1 = super.username1;
	    */
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("chief_editor_email");
		chiefEmail.addItem(name);		
	    }
	    con.close();
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void newCatBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newCatBackActionPerformed
    {//GEN-HEADEREND:event_newCatBackActionPerformed
        new chief_editor().setVisible(true); //Go back to the previous window.
	this.dispose(); // Close previous window.
    }//GEN-LAST:event_newCatBackActionPerformed

    private void chiefEmailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chiefEmailActionPerformed
    {//GEN-HEADEREND:event_chiefEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chiefEmailActionPerformed

    private void parentCatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_parentCatActionPerformed
    {//GEN-HEADEREND:event_parentCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentCatActionPerformed

    private void insertNewCatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_insertNewCatActionPerformed
    {//GEN-HEADEREND:event_insertNewCatActionPerformed
        try
	{
	    Connection con = DriverManager.getConnection(url);
	    Object chief_Email = (Object)chiefEmail.getSelectedItem(); //Get the text from the ComboBox
	    String email = chiefEmail.getSelectedItem().toString();
	    Object parent_Cat = (Object)parentCat.getSelectedItem(); //Get the text from the ComboBox 2
	    String parentcat = parentCat.getSelectedItem().toString();
	    String catname = newCatName.getText(); //Get the text from text box
	    String catdesc = newCatDesc.getText(); //Get the text from text box
	    CallableStatement cs = con.prepareCall("{ call newCat(?,?,?,?)}"); //Call the stored procedure newCat from server
	    cs.setString(1,catname);
	    cs.setString(2,catdesc);                      //INPUTS FOR SPROC
	    cs.setString(3,email);
	    cs.setString(4,parentcat);
	    cs.execute();	    
	    
	    /*
	    System.out.println(email);	      //TESTING    HANDLE EMPTY CAT NAME AND DESCRIPTION CASE
	    System.out.println(parentcat);    //TESTING
	    System.out.println(catname);      //TESTING
	    System.out.println(catdesc);      //TESTING
	    */
	    
	    
	    con.close();
	}
	catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_insertNewCatActionPerformed

    private void newCatNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newCatNameActionPerformed
    {//GEN-HEADEREND:event_newCatNameActionPerformed
        
               
    }//GEN-LAST:event_newCatNameActionPerformed

    private void newCatNameMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_newCatNameMouseClicked
    {//GEN-HEADEREND:event_newCatNameMouseClicked
        newCatName.setText(""); //Clear the initial text when you click in the text field.
    }//GEN-LAST:event_newCatNameMouseClicked

    private void newCatDescMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_newCatDescMouseClicked
    {//GEN-HEADEREND:event_newCatDescMouseClicked
        newCatDesc.setText(""); //Clear the initial text when you click in the text field.
    }//GEN-LAST:event_newCatDescMouseClicked

    private void newCatDescActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newCatDescActionPerformed
    {//GEN-HEADEREND:event_newCatDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCatDescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try
	{
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
	    {
		if ("Nimbus".equals(info.getName()))
		{
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex)
	{
	    java.util.logging.Logger.getLogger(newCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex)
	{
	    java.util.logging.Logger.getLogger(newCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex)
	{
	    java.util.logging.Logger.getLogger(newCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex)
	{
	    java.util.logging.Logger.getLogger(newCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable()
	{
	    public void run()
	    {
		new newCat().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chiefEmail;
    private javax.swing.JButton insertNewCat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton newCatBack;
    private javax.swing.JTextField newCatDesc;
    private javax.swing.JTextField newCatName;
    private javax.swing.JComboBox<String> parentCat;
    // End of variables declaration//GEN-END:variables
}
