/*
 *  Developed by Vasileios Karachountris and Eva Konstantopoulou for Computer Engineering and
 *  Informatics Department, to be used in the Database Laboratory Project that they submit.
 *  All Rights Reserved.
 */
package mainpackage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.*;
import static mainpackage.CheckConnection.url;

/**
 *
 * @author konst
 */
public class newspaperEditing extends javax.swing.JFrame {

    /**
     * Creates new form newspaperEditing
     */
    public newspaperEditing() 
    {
        initComponents();
        FillComboNewspaper();
        FillComboOwner();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        newspaperCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ownerCombo = new javax.swing.JComboBox<>();
        frequencyCombo = new javax.swing.JComboBox<>();
        UsernameText = new javax.swing.JTextField();
        ViewButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please enter your username:");

        ConfirmButton.setText("Confirm Changes");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        newspaperCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newspaperComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Publication Frequency:");

        jLabel4.setText("Owner's name:");

        ownerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerComboActionPerformed(evt);
            }
        });

        frequencyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly", "Monthly" }));

        UsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextActionPerformed(evt);
            }
        });

        ViewButton.setText("View");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Newspaper name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(128, 128, 128))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(172, 172, 172)
                                                .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(73, 73, 73)
                                        .addComponent(ViewButton))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(newspaperCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ownerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(172, 172, 172)
                                            .addComponent(frequencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 421, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(ConfirmButton)
                        .addGap(83, 83, 83)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newspaperCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frequencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmButton)
                    .addComponent(jButton2))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void FillComboOwner()
    {
	try
	{
            UsernameText.getText();
            String thisUser = UsernameText.getText();
	    Connection con = DriverManager.getConnection(url);
	    String sql2 = "SELECT employee_name FROM employee WHERE employee_login = '"+thisUser+"'";
            String sql3 = "SELECT employee_lastname FROM employee WHERE employee_login = '"+thisUser+"'";
            String sql1 = sql2 + sql3;
            // System.out.println(sql1);   Troubleshooting print to eastablish if concat is working as intended
	    PreparedStatement pst = con.prepareStatement(sql1);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("employee_name");
		ownerCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void FillComboNewspaper()
    {
	try
	{
            UsernameText.getText();
            String thisUser = UsernameText.getText();
	    Connection con = DriverManager.getConnection(url);
            String sql = "SELECT newspaper_name FROM employee WHERE employee_login = '"+thisUser+"'";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("newspaper_name");
		newspaperCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  

    
     private void InsertTextIntoDB()
     {
         try
	{
	    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	    //String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "UPDATE newspaper SET publication_frequency= '";
            Object varName1 = (Object)frequencyCombo.getSelectedItem();
            Object varName2 = (Object)newspaperCombo.getSelectedItem();
            String value1 = frequencyCombo.getSelectedItem().toString();
            String value2 = newspaperCombo.getSelectedItem().toString(); 
            String sql1 = sql.concat(value1);   // Combining Initial query with the text from comboBox
	    String sql2 ="' WHERE newspaper_name ='";                //  Adding the final elements of the query
	    String sql3 = sql1.concat(sql2); //
            String sql4 = sql3.concat(value2);
            String sql5 = "';";
            String sql6 = sql4.concat(sql5);
            //System.out.println(sql6);  Troubleshooting print to eastablish if concat is working as intended
            PreparedStatement pst = con.prepareStatement(sql6);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Update successful");
            con.close();
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
     }
     
     private void ChangeOwnerActionPerformed(java.awt.event.ActionEvent evt)                                              
    {                                                  
        try
	{
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SET NOCOUNT ON UPDATE newspaper SET owner_name='"; //Initial SQL query to update a column
	    Object varName = (Object)newspaperCombo.getSelectedItem(); //Get the text from the ComboBox
            Object varName2 = (Object)ownerCombo.getSelectedItem();
            String value1 = ownerCombo.getSelectedItem().toString();
	    String value2 = newspaperCombo.getSelectedItem().toString(); // And pass it to a string.
	    String sql1 = sql.concat(value1);   // Combining Initial query with the text from comboBox
	    String sql2 =" '";                //  Adding the final elements of the query
            String sql3 = sql1.concat(sql2);
            String sql4 = " WHERE newspaper_name ='";
	    String sql5 = sql3.concat(sql4); //
	    //System.out.println(sql3); //Troubleshooting print to eastablish if concat is working as intended
	    PreparedStatement pst = con.prepareStatement(sql5);
	    ResultSet rs = pst.executeQuery();
	    con.close();
	}
	catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
    }                                             
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.hide();
       publisher pb = new publisher();
       pb.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ownerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerComboActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConfirmButtonActionPerformed
    {//GEN-HEADEREND:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
       InsertTextIntoDB(); 
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void UsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextActionPerformed
        // TODO add your handling code here:
        UsernameText.getText();
    }//GEN-LAST:event_UsernameTextActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        FillComboOwner();
        FillComboNewspaper();
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void newspaperComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newspaperComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newspaperComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newspaperEditing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newspaperEditing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newspaperEditing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newspaperEditing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newspaperEditing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JButton ViewButton;
    private javax.swing.JComboBox<String> frequencyCombo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> newspaperCombo;
    private javax.swing.JComboBox<String> ownerCombo;
    // End of variables declaration//GEN-END:variables
}
