/*
 *  Developed by Vasileios Karachountris and Eva Konstantopoulou for Computer Engineering and
 *  Informatics Department, to be used in the Database Laboratory Project that they submit.
 *  All Rights Reserved.
 */
package mainpackage;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.*;
//import net.proteanit.sql.DbUtils;
import static mainpackage.CheckConnection.url;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author User
 */
public class submitArticleforchief extends javax.swing.JFrame {

    /**
     * Creates new form submitArticleforchief
     */
    public submitArticleforchief() {
        initComponents();
        FillTable();
    }
private void FillTable()
    {
	try
	{
	    Connection con = DriverManager.getConnection(url);
	    String sql ="SELECT * FROM article";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    //Fill JTable with the info from the database.
	    ArticleTable.setModel(DbUtils.resultSetToTableModel(rs));
	    
	    //DefaultTableModel tableModel = new DefaultTableModel(data, columns);
	    //ArticleTable.setModel(tableModel);
	    
	    
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PageNumText = new javax.swing.JTextField();
        EditorEmailText = new javax.swing.JTextField();
        ChiefEditorCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        ViewButton = new javax.swing.JButton();
        statusText = new javax.swing.JTextField();
        dateApprove = new javax.swing.JTextField();
        startPage = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ArticleTable = new javax.swing.JTable();
        SubmitButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PathText = new javax.swing.JTextField();
        TitleText = new javax.swing.JTextField();
        SummaryText = new javax.swing.JTextField();
        PagesText = new javax.swing.JTextField();
        KeyWordText = new javax.swing.JTextField();
        CategoryText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please enter the compartments of the article you want to submit :");

        PageNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PageNumTextActionPerformed(evt);
            }
        });

        EditorEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorEmailTextActionPerformed(evt);
            }
        });

        ChiefEditorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "evakn@upatras.gr", "vaskar@upatras.gr" }));
        ChiefEditorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiefEditorComboActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ViewButton.setText("View");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        statusText.setEditable(false);
        statusText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusText.setText("accepted");
        statusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextActionPerformed(evt);
            }
        });

        dateApprove.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateApprove.setText("YYYY-MM-DD");
        dateApprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateApproveMouseClicked(evt);
            }
        });

        startPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ArticleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Path", "Title", "Summary", "Pages", "Status", "Key Word", "Chief Editor Email", "Category ID", "Page Number", "Approve Date", "Page Start", "Editor Email"
            }
        ));
        ArticleTable.setToolTipText("");
        ArticleTable.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(ArticleTable);

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Path:");

        jLabel3.setText("Title:");

        jLabel4.setText("Summary:");

        jLabel5.setText("Pages:");

        jLabel6.setText("KeyWords:");

        jLabel7.setText("Category:");

        jLabel9.setText("Page Number:");

        jLabel10.setText("Editor Email:");

        jLabel11.setText("Status");

        jLabel12.setText("Starting Page:");

        jLabel13.setText("Chief Editor:");

        jLabel14.setText("Date of Approval:");

        PathText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathTextActionPerformed(evt);
            }
        });

        TitleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleTextActionPerformed(evt);
            }
        });

        SummaryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryTextActionPerformed(evt);
            }
        });

        PagesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagesTextActionPerformed(evt);
            }
        });

        KeyWordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyWordTextActionPerformed(evt);
            }
        });

        CategoryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SummaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PagesText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PathText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CategoryText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(KeyWordText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PageNumText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditorEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(startPage, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChiefEditorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ViewButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SubmitButton)
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(ExitButton)
                            .addGap(176, 176, 176)
                            .addComponent(jButton1)
                            .addGap(13, 13, 13))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(CategoryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(KeyWordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(ChiefEditorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PagesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(PageNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(dateApprove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SummaryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(EditorEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(startPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(227, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SubmitButton)
                        .addComponent(ExitButton)
                        .addComponent(jButton1)
                        .addComponent(ViewButton))
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PageNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PageNumTextActionPerformed
        // TODO add your handling code here:
        PageNumText.getText();
    }//GEN-LAST:event_PageNumTextActionPerformed

    private void EditorEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorEmailTextActionPerformed
        // TODO add your handling code here:
        EditorEmailText.getText();
    }//GEN-LAST:event_EditorEmailTextActionPerformed

    private void ChiefEditorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiefEditorComboActionPerformed
        // TODO add your handling code here:
        ChiefEditorCombo.getSelectedItem();
    }//GEN-LAST:event_ChiefEditorComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PathText.setText(" ");
        TitleText.setText(" ");
        SummaryText.setText(" ");
        PagesText.setText(" ");
        KeyWordText.setText(" ");
        dateApprove.setText(" ");
        ChiefEditorCombo.setSelectedIndex(0);
        statusText.setText(" ");
        startPage.setText(" ");
        EditorEmailText.setText(" ");
        PageNumText.setText(" ");
        CategoryText.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        String value1 = PathText.getText();
        System.out.println(value1);
        String value2 = TitleText.getText();
        System.out.println(value2);
        Integer value3 = Integer.parseInt(PagesText.getText());
        System.out.println(value3);
        String value4 = statusText.getText();
        System.out.println(value4);
        String value5 = SummaryText.getText();
        System.out.println(value5);
        String value6 = KeyWordText.getText();
        System.out.println(value6);
        String value7 = ChiefEditorCombo.getSelectedItem().toString();
        System.out.println(value7);
        Integer value8 = Integer.parseInt(CategoryText.getText());
        System.out.println(value8);
        Integer value9 = Integer.parseInt(PageNumText.getText());
        System.out.println(value9);
        String value10 = dateApprove.getText();
        System.out.println(value10);
        String value11 = EditorEmailText.getText();
        System.out.println(value11);
        Integer value12 = Integer.parseInt(startPage.getText());
        System.out.println(value12);
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void statusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextActionPerformed

    private void dateApproveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateApproveMouseClicked
        // TODO add your handling code here:
        dateApprove.setText(" ");
    }//GEN-LAST:event_dateApproveMouseClicked

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con = DriverManager.getConnection(url);
            String value1 = PathText.getText();
            String value2 = TitleText.getText();
            Integer value3 = Integer.parseInt(PagesText.getText());
            String value4 = statusText.getText();
            String value5 = SummaryText.getText();
            String value6 = KeyWordText.getText();
            String value7 = ChiefEditorCombo.getSelectedItem().toString();
            Integer value8 = Integer.parseInt(CategoryText.getText());
            Integer value9 = Integer.parseInt(PageNumText.getText());
            String value10 = dateApprove.getText();
            String value11 = EditorEmailText.getText();
            Integer value12 = Integer.parseInt(startPage.getText());
            CallableStatement cs = con.prepareCall("{ call submitArticle(?,?,?,?,?,?,?,?,?,?,?,?)}");
            cs.setString(1,value1);
            cs.setString(2,value2);
            cs.setInt(3,value3);
            cs.setString(4,value4);
            cs.setString(5,value5);
            cs.setString(6,value6);
            cs.setString(7,value7);
            cs.setInt(8,value8);
            cs.setInt(9,value9);
            cs.setString(10,value10);
            cs.setString(11,value11);
            cs.setInt(12,value12);
            cs.execute();
            con.close();
            /*
            String sql = "UPDATE article SET pages ='' WHERE title = 'The Greek Borders'";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeQuery();
            String value1 = PathText.getText();
            pst.setString(1,value1);
            String value2 = TitleText.getText();
            pst.setString(2, value2);
            Integer value3 = Integer.parseInt(PagesText.getText());
            pst.setInt(3, value3);
            String value4 = StatusCombo.getSelectedItem().toString();
            pst.setString(4, value4);
            String value5 = SummaryText.getText();
            pst.setString(5, value5);
            String value6 = KeyWordText.getText();
            pst.setString(6, value6);
            String value7 = ChiefEditorCombo.getSelectedItem().toString();
            pst.setString(7, value7);
            Integer value8 = Integer.parseInt(CategoryText.getText());
            pst.setInt(8, value8);
            Integer value9 = Integer.parseInt(PageNumText.getText());
            pst.setInt(9, value9);
            Integer value10 = null;
            pst.setInt(10, value10);
            String value11 = EditorEmailText.getText();
            pst.setString(11, value11);
            Integer value12 = 10;
            pst.setInt(12, value12);
            pst.executeQuery();
            JOptionPane.showMessageDialog(null,"insertion successful");
            con.close();
            */
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        new chief_editor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void PathTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathTextActionPerformed
        // TODO add your handling code here:
        PathText.getText();
    }//GEN-LAST:event_PathTextActionPerformed

    private void TitleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleTextActionPerformed
        // TODO add your handling code here:
        TitleText.getText();
    }//GEN-LAST:event_TitleTextActionPerformed

    private void SummaryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryTextActionPerformed
        // TODO add your handling code here:
        SummaryText.getText();
    }//GEN-LAST:event_SummaryTextActionPerformed

    private void PagesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagesTextActionPerformed
        // TODO add your handling code here:
        PagesText.getText();
    }//GEN-LAST:event_PagesTextActionPerformed

    private void KeyWordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyWordTextActionPerformed
        // TODO add your handling code here:
        KeyWordText.getText();
    }//GEN-LAST:event_KeyWordTextActionPerformed

    private void CategoryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryTextActionPerformed
        // TODO add your handling code here:
        CategoryText.getText();
    }//GEN-LAST:event_CategoryTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(submitArticleforchief.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(submitArticleforchief.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(submitArticleforchief.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(submitArticleforchief.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new submitArticleforchief().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ArticleTable;
    private javax.swing.JTextField CategoryText;
    private javax.swing.JComboBox<String> ChiefEditorCombo;
    private javax.swing.JTextField EditorEmailText;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField KeyWordText;
    private javax.swing.JTextField PageNumText;
    private javax.swing.JTextField PagesText;
    private javax.swing.JTextField PathText;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField SummaryText;
    private javax.swing.JTextField TitleText;
    private javax.swing.JButton ViewButton;
    private javax.swing.JTextField dateApprove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField startPage;
    private javax.swing.JTextField statusText;
    // End of variables declaration//GEN-END:variables
}
